title: Dylan Rhymaun
email: rhymaundylan@gmail.com
description: >-
  Personal website for Dylan Rhymaun
baseurl: "/main" 
url: "https://github.com/DylanRhymaun" # your GitHub Pages URL

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Collections (optional, for organizing different types of content)
collections:
  articles:
    output: true
    permalink: /:collection/:name/

# Exclude files/folders from being processed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock